ARG HAWKSET_VERSION=latest
FROM hawkset-exp:${HAWKSET_VERSION}

RUN apt update
RUN apt install -y autoconf automake build-essential cmake libsnappy-dev \
    libbz2-dev zlib1g-dev libgflags-dev

RUN apt install -y libpmemobj-dev

WORKDIR $TOOL_ROOT
RUN git clone https://github.com/DICL/FAST_FAIR

##### FAST_FAIR
WORKDIR $TOOL_ROOT/FAST_FAIR
RUN git checkout 0f047e8
WORKDIR $TOOL_ROOT/FAST_FAIR/concurrent_pmdk

# Apply patch
RUN git apply $TOOL_ROOT/patches/fast_fair.diff
# Compile
RUN make
