ARG HAWKSET_VERSION=latest
FROM hawkset-exp:${HAWKSET_VERSION}

RUN apt update
RUN apt install -y autoconf automake build-essential cmake \
    intel-mkl libpmemobj-cpp-dev

WORKDIR $TOOL_ROOT
RUN git clone https://github.com/olemon111/WIPE

##### WIPE
WORKDIR $TOOL_ROOT/WIPE

RUN git apply $TOOL_ROOT/patches/wipe.diff

RUN mkdir -p build
WORKDIR $TOOL_ROOT/WIPE/build
RUN cmake -DCMAKE_BUILD_TYPE=Debug ..
RUN make -j

