FROM hawkset

RUN apt install -y libgflags-dev libpmemobj-dev libpmem-dev libvmem-dev

WORKDIR $TOOL_ROOT
RUN git clone https://github.com/hansonzhao007/TurboHash

WORKDIR $TOOL_ROOT/TurboHash
RUN git submodule init
RUN git submodule update

COPY patches $TOOL_ROOT/patches

# Apply patch
RUN git apply --ignore-space-change --ignore-whitespace $TOOL_ROOT/patches/turbohash.diff
# Compile
RUN bash buildall.sh ; exit 0
RUN bash buildall.sh
