FROM hawkset

RUN apt install -y scons libconfig-dev libitm1 libpmemobj-cpp-dev

WORKDIR $TOOL_ROOT
RUN git clone https://github.com/urcs-sync/Montage

##### Montage
WORKDIR $TOOL_ROOT/Montage

COPY patches $TOOL_ROOT/patches

# Apply patch
RUN git apply $TOOL_ROOT/patches/montage.diff
# Compile
RUN make debug

ENV LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:$TOOL_ROOT/Montage/ext/mod-single-repo/nvm_malloc/
